name: Simple CI job

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Print message with date
        run: |
  echo "Current date and time: $(date)"
